/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.clase2.diaz.operacionesbd;

import com.clase2.diaz.DAO.CLSjoinpersonaestudiante;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PREDATOR
 */
public class joinEstudiantePersona extends javax.swing.JPanel {

    /**
     * Creates new form joinEstudiantePersona
     */
    public joinEstudiantePersona() {
        initComponents();
        String Titulos[] = {"NOMBRE", "APELLIDO", "MATRICULA"};
        DefaultTableModel df = new DefaultTableModel(null, Titulos);
        CLSjoinpersonaestudiante CLSJOINPE = new CLSjoinpersonaestudiante();
        var MostrarJoinEstudiantePersona = CLSJOINPE.MostrarJoinEstudiantePersona();
        String filas[] = new String[4];

        for (var iterador : MostrarJoinEstudiantePersona) {
            filas[0] = iterador.getNombre();
            filas[1] = iterador.getApellido();
            filas[2] = String.valueOf(iterador.getMatricula());
            df.addRow(filas);

        }
        JTJoinEstudiantePersona.setModel(df);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        JTJoinEstudiantePersona = new javax.swing.JTable();

        JTJoinEstudiantePersona.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(JTJoinEstudiantePersona);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTJoinEstudiantePersona;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
